import type { CategoryKey } from '@/types/content';

interface Quote {
  text: string;
  author: string;
}

const CATEGORY_QUOTES: Record<CategoryKey, Quote[]> = {
  science: [
    { text: '상상력은 지식보다 중요하다.', author: '알베르트 아인슈타인' },
    { text: '과학은 사실의 바다에서 진리를 낚는 것이다.', author: '아이작 뉴턴' },
    { text: '모든 위대한 발견은 대담한 추측에서 시작된다.', author: '아이작 아시모프' },
    { text: '자연은 수학의 언어로 쓰여 있다.', author: '갈릴레오 갈릴레이' },
    { text: '호기심은 과학의 어머니다.', author: '토마스 에디슨' },
  ],
  psychology: [
    { text: '인간은 자신이 생각하는 대로 된다.', author: '윌리엄 제임스' },
    { text: '아는 것이 힘이 아니라, 아는 것을 실행하는 것이 힘이다.', author: '알프레드 아들러' },
    { text: '무의식은 정신의 더 큰 원이다.', author: '지그문트 프로이트' },
    { text: '사람은 의미를 찾을 때 어떤 고통도 견딜 수 있다.', author: '빅토르 프랭클' },
    { text: '습관이 바뀌면 인생이 바뀐다.', author: '아리스토텔레스' },
  ],
  people: [
    { text: '세상을 바꾸는 것은 평범한 사람들의 비범한 용기다.', author: '마하트마 간디' },
    { text: '천 리 길도 한 걸음부터.', author: '노자' },
    { text: '실패는 성공의 어머니다.', author: '토마스 에디슨' },
    { text: '위대한 일은 충동이 아니라 작은 일의 연속으로 이루어진다.', author: '빈센트 반 고흐' },
    { text: '나는 실패한 것이 아니라 작동하지 않는 방법을 발견한 것이다.', author: '토마스 에디슨' },
  ],
  history: [
    { text: '역사를 잊은 민족에게 미래는 없다.', author: '윈스턴 처칠' },
    { text: '과거에서 배우지 않는 자는 그것을 반복하게 된다.', author: '조지 산타야나' },
    { text: '역사는 승자의 기록이 아니라 인간의 이야기다.', author: '하워드 진' },
    { text: '오늘의 역사가 내일의 전설이 된다.', author: '맥아더' },
    { text: '우리가 역사에서 배운 것은, 아무것도 배우지 못했다는 것이다.', author: '헤겔' },
  ],
  koreanhistory: [
    { text: '신에게는 아직 열두 척의 배가 있사옵니다.', author: '이순신' },
    { text: '백성을 위한 새 문자를 만들었으니, 이것이 훈민정음이다.', author: '세종대왕' },
    { text: '역사를 잊은 민족에게 미래는 없다.', author: '신채호' },
    { text: '나라가 위태롭거든 죽음으로써 지켜라.', author: '이황' },
    { text: '어두운 밤이 지나면 반드시 밝은 새벽이 온다.', author: '김구' },
  ],
  life: [
    { text: '삶이 있는 한 희망은 있다.', author: '키케로' },
    { text: '인생은 가까이서 보면 비극이지만 멀리서 보면 희극이다.', author: '찰리 채플린' },
    { text: '오늘 할 수 있는 일을 내일로 미루지 마라.', author: '벤자민 프랭클린' },
    { text: '행복은 습관이다. 그것을 몸에 지녀라.', author: '허버트' },
    { text: '지금 이 순간을 살아라.', author: '마르쿠스 아우렐리우스' },
  ],
  business: [
    { text: '혁신은 리더와 추종자를 구분하는 잣대다.', author: '스티브 잡스' },
    { text: '기회는 준비된 자에게 온다.', author: '루이 파스퇴르' },
    { text: '성공은 열정을 잃지 않고 실패에서 실패로 걸어가는 것이다.', author: '윈스턴 처칠' },
    { text: '가장 큰 위험은 아무 위험도 감수하지 않는 것이다.', author: '마크 저커버그' },
    { text: '고객이 원하는 것을 주지 말고, 필요한 것을 만들어라.', author: '스티브 잡스' },
  ],
  culture: [
    { text: '예술은 자연이 만들지 못한 것을 완성한다.', author: '아리스토텔레스' },
    { text: '모든 예술은 무용하다. 그것이 예술의 매력이다.', author: '오스카 와일드' },
    { text: '음악은 말로 표현할 수 없는 것을 전한다.', author: '빅토르 위고' },
    { text: '문화는 인간이 스스로를 표현하는 방식이다.', author: '에드워드 타일러' },
    { text: '창조는 기존의 것을 새롭게 연결하는 것이다.', author: '스티브 잡스' },
  ],
  origins: [
    { text: '언어의 한계가 곧 세계의 한계다.', author: '루트비히 비트겐슈타인' },
    { text: '말은 생각의 옷이다.', author: '사무엘 존슨' },
    { text: '이름을 아는 것과 이해하는 것은 다르다.', author: '리처드 파인만' },
    { text: '한 민족의 언어는 그 민족의 정신이다.', author: '빌헬름 폰 훔볼트' },
    { text: '단어 하나를 바꾸면 세상이 달라진다.', author: '루이스 캐럴' },
  ],
  etc: [
    { text: '배움에는 끝이 없다.', author: '공자' },
    { text: '호기심은 인간의 가장 위대한 미덕이다.', author: '알베르트 아인슈타인' },
    { text: '세상에서 가장 아름다운 것은 보이지 않는 것이다.', author: '생텍쥐페리' },
    { text: '아는 만큼 보인다.', author: '유홍준' },
    { text: '질문하는 자가 5분 바보라면, 질문하지 않는 자는 영원한 바보다.', author: '중국 속담' },
  ],
};

const CARD_QUOTES: Record<string, Quote> = {
  // ── business ──────────────────────────────────────────────────────────────
  'airbnb-origin': { text: '아이디어는 실행 없이는 아무것도 아니다.', author: '토마스 에디슨' },
  'amazon-flywheel': { text: '성장은 선순환에서 온다.', author: '제프 베이조스' },
  'apple-comeback': { text: '혁신은 천 가지를 거절하는 것이다.', author: '스티브 잡스' },
  'blue-ocean': { text: '경쟁은 전략의 실패다.', author: '마이클 포터' },
  'compound-effect': { text: '복리는 세계 8대 불가사의다.', author: '알베르트 아인슈타인' },
  'design-thinking': { text: '사용자를 관찰하라. 그들이 말하는 것이 아니라 행동하는 것을 보라.', author: '헨리 포드' },
  'disruption-theory': { text: '과거의 성공이 미래의 실패를 만든다.', author: '클레이튼 크리스텐슨' },
  'first-mover-myth': { text: '빠른 것이 중요한 게 아니라, 올바른 것이 중요하다.', author: '피터 드러커' },
  'flywheel-effect': { text: '위대함은 단번에 오지 않는다. 꾸준한 축적이다.', author: '짐 콜린스' },
  'freemium-model': { text: '공짜로 줘서 사람을 모으고, 가치로 돈을 받아라.', author: '크리스 앤더슨' },
  'google-garage': { text: '큰 꿈을 꿔라. 차고에서 시작해도 된다.', author: '래리 페이지' },
  'growth-hacking': { text: '성장은 마케팅이 아니라 제품에서 나온다.', author: '션 엘리스' },
  'ikea-effect-biz': { text: '내가 만든 것에 더 높은 가치를 부여한다.', author: '댄 아리얼리' },
  'jobs-to-be-done': { text: '고객은 제품이 아니라 자신의 삶을 구매한다.', author: '클레이튼 크리스텐슨' },
  'lean-startup': { text: '빨리 실패하고, 빨리 배워라.', author: '에릭 리스' },
  'moat-strategy': { text: '훌륭한 사업은 경쟁자를 막는 성을 가지고 있다.', author: '워런 버핏' },
  'mvp-strategy': { text: '완벽한 제품을 만들 때까지 기다리면, 너무 늦는다.', author: '리드 호프먼' },
  'netflix-pivot': { text: '변화에 저항하면 죽는다. 변화를 이끌면 산다.', author: '리드 헤이스팅스' },
  'network-effect': { text: '연결된 노드가 늘어날수록 네트워크의 가치는 기하급수적으로 커진다.', author: '로버트 메트칼프' },
  'nvidia-ai-pivot': { text: '한 산업에 만족하는 순간 다음 산업에 추월당한다.', author: '젠슨 황' },
  'okr-vs-kpi': { text: '올바른 목표는 사람을 올바른 방향으로 움직이게 한다.', author: '앤디 그로브' },
  'pareto-principle': { text: '80%의 결과는 20%의 원인에서 온다.', author: '빌프레도 파레토' },
  'pivot-strategy': { text: '방향을 바꾸는 것은 포기가 아니라 학습이다.', author: '에릭 리스' },
  'platform-business': { text: '플랫폼은 파이프라인보다 크다.', author: '마샬 밴 앨스타인' },
  'product-market-fit': { text: '시장이 원하는 것을 만들면 고객이 당신을 찾아온다.', author: '마크 앤드리슨' },
  'slack-pivot': { text: '실패는 끝이 아니라 새로운 시작의 데이터다.', author: '스튜어트 버터필드' },
  'spotify-model': { text: '자율성과 책임이 함께할 때 팀은 최고가 된다.', author: '핸릭 크니버그' },
  'subscription-economy': { text: '소유보다 경험이 중요한 시대가 왔다.', author: '주오라 창업자 티엔 쭈오' },
  'tesla-master-plan': { text: '지속 가능한 미래는 긴 계획에서 시작된다.', author: '일론 머스크' },
  'toyota-lean': { text: '낭비를 없애는 것이 효율이다.', author: '오노 다이이치' },
  'unit-economics': { text: '숫자가 거짓말을 하지 않는다. 하지만 숫자를 읽는 사람은 거짓말을 한다.', author: '피터 드러커' },

  // ── culture ───────────────────────────────────────────────────────────────
  'anime-history': { text: '애니메이션은 이야기를 통해 불가능한 것을 가능하게 한다.', author: '미야자키 하야오' },
  'banksy-mystery': { text: '예술은 사람들이 생각하지 못하는 방식으로 진실을 말한다.', author: '뱅크시' },
  'beatles-breakup': { text: '모든 좋은 것은 끝이 있다.', author: '영국 속담' },
  'blue-monday-myth': { text: '행복은 날짜가 아니라 태도에 달려 있다.', author: '찰스 다윈' },
  'broken-window': { text: '작은 무질서를 방치하면 큰 혼란이 따른다.', author: '제임스 윌슨' },
  'butterfly-effect': { text: '브라질의 나비가 날갯짓하면 텍사스에 토네이도가 생긴다.', author: '에드워드 로렌츠' },
  'campbell-law': { text: '측정이 목표가 되면, 측정은 의미를 잃는다.', author: '도널드 캠벨' },
  'cobra-effect': { text: '좋은 의도가 나쁜 결과를 낳을 수 있다.', author: '호르스트 시베르트' },
  'dunning-kruger': { text: '무지한 자일수록 자신의 무지를 모른다.', author: '버트런드 러셀' },
  'goodhart-law': { text: '지표가 목표가 되는 순간, 그것은 더 이상 좋은 지표가 아니다.', author: '찰스 굿하트' },
  'hanlon-razor': { text: '악의보다 무지로 설명될 수 있는 것을 악의로 돌리지 마라.', author: '로버트 핸런' },
  'hip-hop-origin': { text: '음악은 혁명을 노래한다.', author: '척 디' },
  'impostor-syndrome': { text: '나는 내가 얼마나 많이 모르는지 알고 있다.', author: '소크라테스' },
  'kpop-global': { text: '문화는 국경을 넘는 가장 강력한 언어다.', author: '반기문' },
  'mere-exposure': { text: '친숙함은 경멸을 낳는다고 하지만, 사실 친숙함은 애정을 낳는다.', author: '로버트 자이언스' },
  'michelin-star': { text: '완벽함은 더 이상 뺄 것이 없을 때 달성된다.', author: '앙투안 드 생텍쥐페리' },
  'mona-lisa-theft': { text: '예술의 가치는 그것을 잃었을 때 비로소 드러난다.', author: '오스카 와일드' },
  'murphy-law': { text: '잘못될 수 있는 것은 반드시 잘못된다.', author: '에드워드 머피' },
  'occams-razor': { text: '필요 이상으로 존재를 늘리지 마라.', author: '윌리엄 오컴' },
  'overton-window': { text: '오늘의 극단이 내일의 상식이 된다.', author: '조지프 오버턴' },
  'parkinson-law': { text: '일은 주어진 시간을 채우기 위해 팽창한다.', author: '시릴 파킨슨' },
  'peter-principle': { text: '모든 사람은 자신의 무능력 수준까지 승진한다.', author: '로런스 피터' },
  'punk-rock': { text: '록은 태도다. 악기가 아니다.', author: '조 스트러머' },
  'sapir-whorf': { text: '언어의 한계가 곧 세계의 한계다.', author: '루트비히 비트겐슈타인' },
  'shakespeare-mystery': { text: '세상은 하나의 무대이고, 모든 남녀는 배우일 뿐이다.', author: '윌리엄 셰익스피어' },
  'stoicism-daily': { text: '네가 통제할 수 없는 것에 마음 쓰지 마라.', author: '에픽테토스' },
  'streisand-effect': { text: '숨기려 할수록 더 드러난다.', author: '인터넷 격언' },
  'studio-ghibli': { text: '상상력이 풍부한 아이들에게 현실을 보여주어라.', author: '미야자키 하야오' },
  'sunk-cost': { text: '이미 엎질러진 물은 다시 담을 수 없다.', author: '서양 속담' },
  'trolley-problem': { text: '도덕은 규칙이 아니라 선택이다.', author: '임마누엘 칸트' },
  'van-gogh-ear': { text: '위대한 예술은 고통 속에서 태어난다.', author: '빈센트 반 고흐' },
  'vinyl-revival': { text: '아날로그는 디지털이 줄 수 없는 온기를 가지고 있다.', author: '잭 화이트' },

  // ── etc ───────────────────────────────────────────────────────────────────
  'ai-turing-test': { text: '기계가 생각할 수 있는가?', author: '앨런 튜링' },
  'axolotl-regeneration': { text: '자연은 우리가 생각하는 것보다 훨씬 창의적이다.', author: '찰스 다윈' },
  'banana-radiation': { text: '모든 것은 독이다. 용량이 독을 만든다.', author: '파라셀수스' },
  'bermuda-triangle': { text: '설명할 수 없는 것이 반드시 신비로운 것은 아니다.', author: '칼 세이건' },
  'birthday-paradox': { text: '직관은 종종 틀린다. 그래서 수학이 필요하다.', author: '존 앨런 파울로스' },
  'bitcoin-origin': { text: '신뢰가 필요 없는 시스템을 만들 수 있다.', author: '사토시 나카모토' },
  'chocolate-history': { text: '초콜릿은 신의 음식이다.', author: '카를 폰 린네' },
  'deja-vu': { text: '기억은 기록이 아니라 재구성이다.', author: '엘리자베스 로프터스' },
  'earworm': { text: '음악은 마음의 단축키다.', author: '올리버 색스' },
  'emoji-history': { text: '그림은 천 마디 말의 가치가 있다.', author: '나폴레온 보나파르트' },
  'fibonacci-nature': { text: '수학은 자연의 언어다.', author: '갈릴레오 갈릴레이' },
  'fortune-cookie': { text: '행운은 스스로 만드는 것이다.', author: '세네카' },
  'four-leaf-clover': { text: '행운은 준비된 마음과 기회가 만나는 것이다.', author: '세네카' },
  'golden-ratio': { text: '아름다움에는 수학적 질서가 있다.', author: '레오나르도 다 빈치' },
  'goldfish-memory': { text: '알려진 사실도 틀릴 수 있다.', author: '칼 세이건' },
  'honeybee-democracy': { text: '집단지성은 개인지성을 능가한다.', author: '토마스 시리' },
  'honey-eternal': { text: '자연은 완벽한 보존법을 알고 있다.', author: '아리스토텔레스' },
  'human-glow': { text: '우리는 별의 먼지로 만들어졌다.', author: '칼 세이건' },
  'instant-noodle': { text: '필요는 발명의 어머니다.', author: '플라톤' },
  'kimchi-science': { text: '발효는 시간이 만드는 예술이다.', author: '한국 속담' },
  'left-handed': { text: '소수가 항상 틀린 것은 아니다.', author: '버트런드 러셀' },
  'left-right-driving': { text: '관습은 법보다 강하다.', author: '로마 법언' },
  'monty-hall': { text: '직관을 의심하는 것이 수학의 시작이다.', author: '폴 에르되시' },
  'octopus-intelligence': { text: '지능은 뇌의 크기가 아니라 복잡성에서 온다.', author: '피터 고드프리스미스' },
  'paper-fold-limit': { text: '단순한 규칙도 반복되면 불가능을 만든다.', author: '수학 격언' },
  'password-123456': { text: '보안은 가장 약한 고리만큼만 강하다.', author: '브루스 슈나이어' },
  'phantom-vibration': { text: '뇌는 없는 것도 만들어낸다.', author: '올리버 색스' },
  'tardigrade-survival': { text: '생명은 놀라울 정도로 회복력이 있다.', author: '찰스 다윈' },
  'umami-secret': { text: '맛은 혀가 아니라 뇌로 느낀다.', author: '이케다 기쿠나에' },
  'why-sky-blue': { text: '자연의 모든 현상에는 이유가 있다.', author: '아이작 뉴턴' },
  'yawning-contagion': { text: '공감은 인간을 인간답게 만드는 것이다.', author: '프란스 드 발' },

  // ── history ───────────────────────────────────────────────────────────────
  'apollo-13': { text: '실패는 선택지가 아니다.', author: '진 크란츠' },
  'berlin-wall': { text: '자유는 나눌 수 없다.', author: '존 F. 케네디' },
  'black-death': { text: '위기는 변화의 씨앗을 품고 있다.', author: '바바라 터크먼' },
  'boston-tea-party': { text: '대표 없이 과세 없다.', author: '미국 독립혁명 격언' },
  'chernobyl': { text: '진실은 반드시 밝혀진다.', author: '소련 속담' },
  'cold-war-space': { text: '경쟁이 인류를 별까지 데려갔다.', author: '닐 암스트롱' },
  'cuban-missile': { text: '외교는 전쟁을 막는 마지막 수단이다.', author: '존 F. 케네디' },
  'dunkirk': { text: '전쟁에서 가장 위대한 승리는 살아서 돌아오는 것이다.', author: '윈스턴 처칠' },
  'easter-island': { text: '문명은 자원을 소비하며 스스로를 파괴한다.', author: '재레드 다이아몬드' },
  'french-revolution': { text: '자유, 평등, 박애.', author: '프랑스 혁명 슬로건' },
  'genghis-khan-tomb': { text: '정복자도 땅에 묻힌다.', author: '몽골 속담' },
  'great-fire-london': { text: '재앙은 종종 재건의 기회가 된다.', author: '새뮤얼 피프스' },
  'hiroshima': { text: '나는 죽음이 되었노라, 세상의 파괴자가 되었노라.', author: '로버트 오펜하이머' },
  'industrial-revolution': { text: '증기기관은 세계를 바꿨다.', author: '제임스 와트' },
  'joseon-hangeul': { text: '나라의 말이 중국과 달라, 백성들이 글을 모른다.', author: '세종대왕 훈민정음 서문' },
  'library-of-alexandria': { text: '책을 불태우는 자는 결국 사람도 불태운다.', author: '하인리히 하이네' },
  'maya-collapse': { text: '문명은 외부의 적이 아닌 내부의 붕괴로 사라진다.', author: '아놀드 토인비' },
  'meiji-restoration': { text: '변화를 두려워하지 말고, 변화하지 않는 것을 두려워하라.', author: '일본 메이지 시대 격언' },
  'moon-landing': { text: '인간에게는 작은 발걸음, 인류에게는 위대한 도약.', author: '닐 암스트롱' },
  'pearl-harbor': { text: '잠자는 거인을 깨웠다.', author: '이소로쿠 야마모토' },
  'pompeii-last-day': { text: '자연은 기다리지 않는다.', author: '플리니우스 소소' },
  'printing-press': { text: '인쇄술은 신의 최고 선물이자 가장 위대한 발명이다.', author: '마르틴 루터' },
  'pyramid-workers': { text: '위대한 건축은 수많은 손으로 만들어진다.', author: '이집트 속담' },
  'roman-fall': { text: '로마는 하루아침에 세워지지 않았다.', author: '서양 속담' },
  'rosetta-stone': { text: '언어의 열쇠가 역사의 문을 연다.', author: '장프랑수아 샹폴리옹' },
  'samurai-last': { text: '죽기를 각오하면 살고, 살기를 각오하면 죽는다.', author: '이순신' },
  'silk-road-secret': { text: '교역은 칼보다 강하다.', author: '마르코 폴로' },
  'spanish-flu': { text: '역사는 반복된다. 특히 무지한 자들에게.', author: '조지 산타야나' },
  'titanic-real-cause': { text: '자만심은 재앙을 부른다.', author: '서양 속담' },
  'trojan-war': { text: '선물로 가장한 속임수를 조심하라.', author: '베르길리우스' },
  'viking-myth': { text: '역사는 승자가 아닌 생존자가 쓴다.', author: '하워드 진' },
  'waterloo': { text: '내 사전에 불가능은 없다. 하지만 워털루가 그것을 바꿨다.', author: '나폴레온 보나파르트' },

  // ── life ──────────────────────────────────────────────────────────────────
  '5am-club': { text: '성공한 사람들은 남들이 자는 시간에 일어난다.', author: '로빈 샤르마' },
  'blue-zone': { text: '오래 사는 비결은 먹는 것, 움직이는 것, 사람과 함께하는 것이다.', author: '댄 뷰에트너' },
  'breathwork': { text: '호흡을 조절하면 마음을 조절할 수 있다.', author: '빔 호프' },
  'circadian-rhythm': { text: '자연의 리듬에 맞춰 살아라.', author: '히포크라테스' },
  'cold-shower': { text: '불편함에 익숙해지면 모든 것이 쉬워진다.', author: '빔 호프' },
  'decision-fatigue': { text: '선택할 것이 적을수록 더 나은 결정을 한다.', author: '배리 슈워츠' },
  'deep-work': { text: '몰입 없이는 위대함도 없다.', author: '칼 뉴포트' },
  'digital-detox': { text: '연결을 끊을 때 비로소 자신과 연결된다.', author: '팀 페리스' },
  'digital-minimalism': { text: '덜 사용할수록 더 잘 살 수 있다.', author: '칼 뉴포트' },
  'dopamine-detox': { text: '즉각적인 보상을 줄여야 더 큰 것을 얻는다.', author: '카메론 세파' },
  'flow-state': { text: '최적의 경험은 완전한 몰입에서 온다.', author: '미하이 칙센트미하이' },
  'forest-bathing': { text: '자연 속에서 걷는 것은 마음의 약이다.', author: '일본 산림청 격언' },
  'gratitude-journal': { text: '감사하는 마음이 행복의 문을 연다.', author: '오프라 윈프리' },
  'gut-brain': { text: '장은 제2의 뇌다.', author: '마이클 거션' },
  'gut-health-food': { text: '음식이 곧 약이다.', author: '히포크라테스' },
  'habit-stacking': { text: '새 습관은 기존 습관에 붙여라.', author: '제임스 클리어' },
  'ikigai': { text: '존재의 이유가 삶에 활력을 준다.', author: '일본 속담' },
  'intermittent-fasting': { text: '먹지 않는 시간이 몸을 치유한다.', author: '마크 맷슨' },
  'journaling-power': { text: '쓰는 것은 생각을 명확하게 하는 가장 좋은 방법이다.', author: '줄리아 캐머런' },
  'meditation-science': { text: '명상은 마음의 체육관이다.', author: '마티유 리카르' },
  'micro-habit': { text: '작은 습관이 놀라운 결과를 만든다.', author: '제임스 클리어' },
  'minimalism-life': { text: '소유할수록 소유에 소유당한다.', author: '헨리 데이비드 소로' },
  'money-saving-latte': { text: '작은 지출이 모여 큰 가난이 된다.', author: '데이비드 바크' },
  'morning-routine': { text: '하루를 어떻게 시작하느냐가 하루를 결정한다.', author: '할 엘로드' },
  'nostalgia-effect': { text: '과거는 현재를 따뜻하게 한다.', author: '콘스탄틴 세디키데스' },
  'placebo-effect': { text: '믿음이 현실을 바꾼다.', author: '노먼 커즌스' },
  'pomodoro-technique': { text: '짧은 집중이 긴 집중보다 효과적이다.', author: '프란체스코 시릴로' },
  'power-nap': { text: '20분의 낮잠은 커피 한 잔보다 강하다.', author: 'NASA 연구 격언' },
  'second-brain': { text: '뇌는 아이디어를 생각하기 위한 것, 저장하기 위한 것이 아니다.', author: '데이비드 앨런' },
  'sleep-hygiene': { text: '수면은 뇌의 청소 시간이다.', author: '마슈 워커' },
  'walking-meditation': { text: '걷는 것은 가장 좋은 약이다.', author: '히포크라테스' },

  // ── origins ───────────────────────────────────────────────────────────────
  'algebra-origin': { text: '대수학은 마음의 음악이다.', author: '제임스 조지프 실베스터' },
  'algorithm': { text: '이름을 아는 것과 이해하는 것은 다르다.', author: '리처드 파인만' },
  'americano': { text: '커피 한 잔에 문화가 담긴다.', author: '이탈리아 속담' },
  'arbeit': { text: '노동이 인간을 만든다.', author: '독일 속담' },
  'assassin-origin': { text: '언어에는 역사가 숨어 있다.', author: '루트비히 비트겐슈타인' },
  'barbecue-origin': { text: '불은 인류의 첫 번째 요리 도구다.', author: '리처드 랭엄' },
  'bluetooth': { text: '소통은 단절을 연결로 바꾼다.', author: '하랄 블로탄드 왕 격언' },
  'boycott': { text: '단결한 사람들은 패배하지 않는다.', author: '찰스 보이콧 격언' },
  'brunch': { text: '두 가지를 합치면 새로운 것이 탄생한다.', author: '영어 격언' },
  'bug': { text: '오류를 찾는 것이 오류를 만드는 것보다 어렵다.', author: '도널드 커누스' },
  'cappuccino': { text: '커피는 문화다.', author: '이탈리아 속담' },
  'carnival-origin': { text: '축제는 인간의 본능이다.', author: '미르체아 엘리아데' },
  'champagne': { text: '샴페인 없이는 승리도 없다.', author: '나폴레온 보나파르트' },
  'checkmate-origin': { text: '왕이 죽으면 게임은 끝난다.', author: '체스 격언' },
  'curfew-origin': { text: '규칙은 필요에서 태어난다.', author: '로마 법언' },
  'deadline': { text: '마감은 창의력의 어머니다.', author: '더글라스 애덤스' },
  'denim-jeans': { text: '패션은 시대의 거울이다.', author: '이브 생로랑' },
  'dollar-sign': { text: '돈의 언어는 세계 공통어다.', author: '애덤 스미스' },
  'freelancer': { text: '자유로운 창이 가장 강하다.', author: '중세 격언' },
  'gaslighting': { text: '진실을 의심하게 만드는 것이 가장 큰 폭력이다.', author: '패트릭 해밀턴 격언' },
  'hot-dog': { text: '음식에는 이야기가 있다.', author: '미국 격언' },
  'hurricane-origin': { text: '자연의 힘 앞에 인간은 작다.', author: '카리브 타이노 격언' },
  'karaoke': { text: '빈 오케스트라가 최고의 무대다.', author: '이노우에 다이스케' },
  'ketchup-origin': { text: '음식도 여행을 한다.', author: '아시아 격언' },
  'la-galbi': { text: '이민자의 지혜가 새로운 음식을 만든다.', author: '한인 이민자 격언' },
  'magazine-origin': { text: '지식의 창고를 만들어라.', author: '아랍 격언' },
  'marathon': { text: '우리가 이겼다!', author: '페이디피데스' },
  'mentor': { text: '스승을 넘어서는 것이 스승에 대한 최고의 경의다.', author: '레오나르도 다 빈치' },
  'motel': { text: '자동차가 세상을 바꿨다.', author: '헨리 포드' },
  'nimby': { text: '모두가 필요하다고 하지만 아무도 원하지 않는다.', author: '도시계획 격언' },
  'ok': { text: '모든 것이 괜찮다.', author: '미국 격언' },
  'panic': { text: '공포는 판단력을 마비시킨다.', author: '그리스 신화 격언' },
  'paparazzi': { text: '카메라는 진실을 포착한다.', author: '페데리코 펠리니' },
  'podcast': { text: '목소리는 세계를 연결한다.', author: '팟캐스트 격언' },
  'quarantine': { text: '인내는 가장 강한 방패다.', author: '베네치아 격언' },
  'robot': { text: '기계에게 노동을, 인간에게 창조를.', author: '카렐 차페크' },
  'sabotage-origin': { text: '저항은 억압에 대한 자연스러운 반응이다.', author: '프랑스 노동 격언' },
  'salary': { text: '소금값 하는 인간이 되어라.', author: '로마 속담' },
  'sandwich': { text: '필요가 발명을 만든다.', author: '샌드위치 백작 격언' },
  'serendipity': { text: '행운은 준비된 마음에 찾아온다.', author: '루이 파스퇴르' },
  'shampoo-origin': { text: '씻는 문화는 문명의 척도다.', author: '인도 격언' },
  'sichimi': { text: '모른 척하는 것도 능력이다.', author: '한국 속담' },
  'sos': { text: '도움을 청하는 것은 용기다.', author: '해양 격언' },
  'spam-mail': { text: '원치 않는 것도 이름을 얻는다.', author: '인터넷 격언' },
  'tattoo': { text: '몸은 영혼의 캔버스다.', author: '폴리네시아 속담' },
  'tip': { text: '감사는 행동으로 표현된다.', author: '영국 격언' },
  'tsunami-origin': { text: '자연의 힘에는 겸손해야 한다.', author: '일본 속담' },
  'vaccine': { text: '예방은 치료보다 낫다.', author: '에드워드 제너 격언' },
  'villain': { text: '악당도 스스로는 영웅이라 생각한다.', author: '체스터턴' },
  'whiskey': { text: '위스키는 물의 정수다.', author: '아일랜드 속담' },
  'wifi': { text: '무선은 세상을 하나로 묶는다.', author: '니콜라 테슬라' },
  'zombie': { text: '죽어도 되살아나는 것이 있다.', author: '하이티 민간 신앙 격언' },

  // ── people ────────────────────────────────────────────────────────────────
  'ada-lovelace': { text: '상상력은 보이지 않는 세계를 발견한다.', author: '에이다 러브레이스' },
  'alan-turing': { text: '기계가 생각할 수 있는가?', author: '앨런 튜링' },
  'albert-einstein': { text: '상상력은 지식보다 중요하다.', author: '알베르트 아인슈타인' },
  'alexander-fleming': { text: '실수는 발견의 어머니다.', author: '알렉산더 플레밍' },
  'amelia-earhart': { text: '모험은 가치 있는 것 자체다.', author: '아멜리아 에어하트' },
  'archimedes': { text: '유레카!', author: '아르키메데스' },
  'beethoven-deaf': { text: '음악은 귀가 아니라 영혼으로 듣는다.', author: '루트비히 판 베토벤' },
  'cleopatra': { text: '지식은 권력보다 강하다.', author: '클레오파트라 격언' },
  'coco-chanel': { text: '패션은 지나가지만 스타일은 영원하다.', author: '코코 샤넬' },
  'frida-kahlo': { text: '나는 폭풍을 그린다. 폭풍 속에서 살아왔으니.', author: '프리다 칼로' },
  'galileo': { text: '그래도 지구는 돈다.', author: '갈릴레오 갈릴레이' },
  'genghis-khan': { text: '하늘 아래 하나의 제국을 세워라.', author: '칭기즈 칸' },
  'hedy-lamarr': { text: '미인은 사랑받는다. 하지만 지혜로운 자는 역사를 바꾼다.', author: '헤디 라마' },
  'hypatia': { text: '스스로 생각하는 것이야말로 진정한 자유다.', author: '히파티아' },
  'jang-yeongshil': { text: '신분이 아니라 재능이 세상을 바꾼다.', author: '장영실 격언' },
  'leonardo-da-vinci': { text: '배움은 마음을 젊게 한다.', author: '레오나르도 다 빈치' },
  'mandela': { text: '나는 패배하지 않는다. 포기하지 않을 뿐이다.', author: '넬슨 만델라' },
  'marie-curie': { text: '두려워하지 마라. 새로운 것도 낯선 것도.', author: '마리 퀴리' },
  'nightingale': { text: '통계는 데이터가 아니라 사람의 이야기다.', author: '플로렌스 나이팅게일' },
  'nikola-tesla': { text: '미래가 내 것임을 알고 있다.', author: '니콜라 테슬라' },
  'oppenheimer': { text: '나는 죽음이 되었노라, 세상의 파괴자가 되었노라.', author: '로버트 오펜하이머' },
  'ramanujan': { text: '신이 나에게 수식을 보여주었다.', author: '스리니바사 라마누잔' },
  'richard-feynman': { text: '설명할 수 없다면, 아직 이해하지 못한 것이다.', author: '리처드 파인만' },
  'rosalind-franklin': { text: '과학은 사실에 기반한다. 이름에 기반하지 않는다.', author: '로절린드 프랭클린' },
  'sejong-the-great': { text: '백성을 가르치는 것이 왕의 첫 번째 임무다.', author: '세종대왕' },
  'socrates-trial': { text: '악법도 법이다. 그러나 진실은 법보다 높다.', author: '소크라테스' },
  'stephen-hawking': { text: '우주가 아무리 복잡해도, 인간의 마음은 그것을 이해한다.', author: '스티븐 호킹' },
  'steve-jobs': { text: '다르게 생각하라.', author: '스티브 잡스' },
  'wangari-maathai': { text: '작은 나무 한 그루가 숲을 되살린다.', author: '왕가리 마타이' },
  'wright-brothers': { text: '12초가 인류의 역사를 바꿨다.', author: '오빌 라이트' },
  'yi-sun-sin': { text: '죽기를 각오하면 살고, 살기를 각오하면 죽는다.', author: '이순신' },

  // ── psychology ────────────────────────────────────────────────────────────
  'anchoring-effect': { text: '첫 번째 정보가 판단의 닻이 된다.', author: '대니얼 카너먼' },
  'availability-heuristic': { text: '쉽게 떠오르는 것이 더 중요하다고 느낀다.', author: '아모스 트버스키' },
  'bandwagon-effect': { text: '많은 사람이 믿는다고 진실이 되지는 않는다.', author: '버트런드 러셀' },
  'barnum-effect': { text: '사람들은 자신을 특별하다고 믿고 싶어한다.', author: '폴 밀' },
  'bobo-doll': { text: '아이들은 보는 것을 배운다.', author: '앨버트 밴듀라' },
  'bystander-effect': { text: '책임이 분산되면 아무도 책임지지 않는다.', author: '존 달리' },
  'change-blindness': { text: '보고 있다고 해서 보이는 것은 아니다.', author: '대니얼 사이먼스' },
  'clustering-illusion': { text: '인간의 뇌는 패턴을 만들도록 설계되어 있다.', author: '토마스 길로비치' },
  'cognitive-dissonance': { text: '인간은 믿음과 행동이 충돌할 때 믿음을 바꾼다.', author: '레온 페스팅거' },
  'cognitive-load': { text: '뇌도 과부하가 걸린다.', author: '존 스웰러' },
  'confirmation-bias': { text: '우리는 믿고 싶은 것을 믿으려 한다.', author: '프란시스 베이컨' },
  'dark-triad': { text: '어둠은 숨기지 않는다. 단지 보이지 않을 뿐이다.', author: '칼 구스타프 융' },
  'framing-effect': { text: '같은 사실도 어떻게 말하느냐에 따라 다르게 받아들여진다.', author: '아모스 트버스키' },
  'groupthink': { text: '만장일치는 위험의 신호다.', author: '어빙 재니스' },
  'halo-effect': { text: '첫인상이 모든 것을 물들인다.', author: '에드워드 손다이크' },
  'learned-helplessness': { text: '통제할 수 없다고 믿으면, 정말로 통제하지 못하게 된다.', author: '마틴 셀리그먼' },
  'loss-aversion': { text: '잃는 고통은 얻는 기쁨의 두 배다.', author: '대니얼 카너먼' },
  'marshmallow-test': { text: '만족을 지연시키는 능력이 성공을 예측한다.', author: '월터 미셸' },
  'mere-ownership': { text: '내 것은 더 좋아 보인다.', author: '리처드 탈러' },
  'milgram-obedience': { text: '권위에 복종하는 것은 인간의 본성이다.', author: '스탠리 밀그램' },
  'paradox-of-choice': { text: '선택지가 많을수록 행복은 줄어든다.', author: '배리 슈워츠' },
  'pavlov-dog': { text: '자극과 반응 사이에는 공간이 있다. 그 공간에 우리의 성장이 있다.', author: '빅토르 프랭클' },
  'peak-end-rule': { text: '우리는 절정과 끝만 기억한다.', author: '대니얼 카너먼' },
  'placebo-nocebo': { text: '믿음은 현실을 만든다.', author: '노먼 커즌스' },
  'pygmalion-effect': { text: '기대는 결과를 만든다.', author: '로버트 로젠탈' },
  'reciprocity-principle': { text: '받으면 돌려주고 싶어진다.', author: '로버트 치알디니' },
  'serial-position': { text: '처음과 끝이 가운데보다 강하다.', author: '헤르만 에빙하우스' },
  'social-proof': { text: '다른 사람이 하면 나도 한다.', author: '로버트 치알디니' },
  'spotlight-effect': { text: '아무도 당신만큼 당신을 보지 않는다.', author: '토마스 길로비치' },
  'stanford-prison': { text: '환경이 인간을 만든다.', author: '필립 짐바르도' },
  'stockholm-syndrome': { text: '생존을 위해 인간은 적도 사랑한다.', author: '닐스 베예로트' },
  'zeigarnik-effect': { text: '끝내지 못한 일이 더 오래 기억된다.', author: '블루마 자이가르닉' },

  // ── science ───────────────────────────────────────────────────────────────
  'antimatter': { text: '우주는 대칭을 좋아한다.', author: '폴 디랙' },
  'artificial-sun': { text: '별을 지구에 가져오는 것이 목표다.', author: '이터 프로젝트 격언' },
  'black-hole-paradox': { text: '정보는 결코 사라지지 않는다.', author: '스티븐 호킹' },
  'brain-plasticity': { text: '뇌는 평생 변한다.', author: '마이클 메르제니크' },
  'crispr-baby': { text: '할 수 있다고 해서 해야 하는 것은 아니다.', author: '제니퍼 다우드나' },
  'cryogenics': { text: '죽음은 해결해야 할 문제다.', author: '로버트 에팅어' },
  'dark-matter': { text: '보이지 않는 것이 우주를 지배한다.', author: '프리츠 츠비키' },
  'deep-sea-creatures': { text: '빛이 없는 곳에도 생명은 있다.', author: '윌리엄 비브' },
  'dna-crispr': { text: '유전자는 운명이 아니라 코드다.', author: '제니퍼 다우드나' },
  'dopamine-mechanism': { text: '쾌락이 아니라 욕망의 분자다.', author: '켄트 베리지' },
  'entropy-simple': { text: '모든 것은 무질서를 향해 흐른다.', author: '루트비히 볼츠만' },
  'fermi-paradox': { text: '모두가 어디 있는가?', author: '엔리코 페르미' },
  'gravitational-waves': { text: '우주는 파동으로 속삭인다.', author: '킵 손' },
  'gut-microbiome': { text: '우리는 미생물과 공생하는 생태계다.', author: '롭 나이트' },
  'higgs-boson': { text: '질량의 기원을 찾았다.', author: '피터 힉스' },
  'mars-terraforming': { text: '인류는 한 행성에 머물 수 없다.', author: '일론 머스크' },
  'meteorite-dinosaur': { text: '대멸종은 진화의 리셋 버튼이다.', author: '루이스 앨버레즈' },
  'neutrino': { text: '유령 입자는 모든 것을 통과한다.', author: '볼프강 파울리' },
  'nuclear-fusion': { text: '별이 에너지를 만드는 방법을 지구에서 재현한다.', author: '한스 베테' },
  'ocean-deep': { text: '우리는 달보다 심해를 덜 안다.', author: '실비아 얼' },
  'parallel-universe': { text: '모든 가능성은 어딘가에서 현실이다.', author: '휴 에버렛' },
  'plate-tectonics': { text: '대륙은 움직인다.', author: '알프레트 베게너' },
  'quantum-computing': { text: '양자는 동시에 모든 것이 될 수 있다.', author: '리처드 파인만' },
  'quantum-entanglement': { text: '신은 주사위를 던지지 않는다.', author: '알베르트 아인슈타인' },
  'relativity-twin': { text: '시간은 절대적이지 않다.', author: '알베르트 아인슈타인' },
  'schrodinger-cat': { text: '관측하기 전에는 모든 것이 가능하다.', author: '에르빈 슈뢰딩거' },
  'solar-system-edge': { text: '우리는 우주의 끝을 향해 여행을 보냈다.', author: '칼 세이건' },
  'stem-cell': { text: '생명은 스스로를 재생할 능력을 가지고 있다.', author: '제임스 톰슨' },
  'superconductor': { text: '저항이 사라지면 에너지도 사라지지 않는다.', author: '헤이케 카메를링 오너스' },
  'time-travel': { text: '과거는 변할 수 없지만 미래는 열려 있다.', author: '스티븐 호킹' },
  'voyager-golden-record': { text: '우주에 띄운 병 속의 편지.', author: '칼 세이건' },
  // koreanhistory
  'hangul-creation': { text: '어린 백성이 이르고자 하는 바 있어도 마침내 제 뜻을 능히 펴지 못하는 자가 많으니라.', author: '세종대왕' },
};

/** Pick a quote for a card: slug-specific first, then category fallback */
export function getQuoteForCard(slug: string, category: CategoryKey): Quote {
  // 1. slug 전용 명언이 있으면 우선 사용
  if (CARD_QUOTES[slug]) return CARD_QUOTES[slug];

  // 2. 없으면 기존 카테고리 폴백 (slug 해시 기반 결정론적 선택)
  const quotes = CATEGORY_QUOTES[category] || CATEGORY_QUOTES.etc;
  let hash = 0;
  for (let i = 0; i < slug.length; i++) {
    hash = ((hash << 5) - hash + slug.charCodeAt(i)) | 0;
  }
  return quotes[Math.abs(hash) % quotes.length];
}
